# -*- coding: utf-8 -*-
"""Guess the Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uINQ5QKTJgOFTWwWei1DeMEBzPTOhhUy
"""

import random
number= random.randint(1,10)
print("You will have three chances to guess the correct number!")
for i in range(0,3):
  user= int(input("Guess the Number: "))
  if user==number:
    print("Hurray!")
    print(f"you guessed the number right it's {number}")
    break
if user != number:
  print(f"Your guess is incorrect. The correct number is {number}.")